# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/new/LFSR.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/imports/new/Selector.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/VGA_Display.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/car.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/new/countUD4L.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/CSE 100/Lab 4/Lab4/Lab4.srcs/sources_1/new/counterUD16L.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 6/project_1/project_1.srcs/sources_1/imports/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/imports/new/counterUD16L.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/new/counterUD16L.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/crash_check.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/CSE 100/Lab 4/Lab4/Lab4.srcs/sources_1/new/edge_detector.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/imports/new/hex7seg.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/imports/Lab 7/lab7_clks.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/imports/new/m8_1.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 5/project_test/project_test.srcs/sources_1/imports/new/ring_counter.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/roadSegs.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/state_machine.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/vga_seg_control.v}
  {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/sources_1/new/top_level.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/constrs_1/imports/CSE 100/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_allsegswork/project_allsegswork.srcs/constrs_1/imports/CSE 100/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
