# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/.Xil/Vivado-23976-DESKTOP-AN2HNRA/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 5/LFSR.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 5/Selector.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/VGA_Display.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/car.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/new/countUD4L.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 4/counterUD16L.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/counterUD16L.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/new/counterUD16L.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/crash_check.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 4/edge_detector.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 5/hex7seg.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/Lab 7/lab7_clks.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 5/m8_1.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/imports/CSE 100/Lab 5/ring_counter.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/roadSegs.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/state_machine.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/vga_seg_control.v}
      {C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/project_almostdone.srcs/sources_1/new/top_level.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_level
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Rahul/Google Drive/UCSC/year 2/Winter Quarter/CSE 100/Lab 7/project_almostdone/.Xil/Vivado-23976-DESKTOP-AN2HNRA/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
